#!/bin/bash

# ############################################################################
# Author: 		Matthieu Holtz
# Year:   		2019
# Project: 		photomaton
# Description: 		Script that contains helper functions for photomaton
#
# ############################################################################

# Echo a message and add OK or NOK depending on status code.
# $1 : the status code to check
# $2 : the message to echo
EchoStatus()
{
	if [ $1 -eq 0 ]; then
  		#echo -e "$2...\t\t\t\e[42mOK\e[0m"
  		printf '%s\e[1;34m%8s\e[m\n' "$2..." "[OK]"
	else
  		#echo -e "$2...\t\t\t\e[41mNOK\e[0m"
  		printf '%s\e[1;34m%8s\e[m\n' "$2..." "[NOK]"
	fi
}
